class BaleError(Exception):

    def __init__(self):
        pass
